language: ruby
cache:
  directories:
    - bundle

rvm:
  - 2.3.1
  - 2.1.9
  - 2.0

bundler_args: "--without documentation --path bundle"

before_install:
  - git fetch --depth=1000000
  - gem install bundler

after_install:
  - rake install

script:
  # Tests use real git commands
  - git config --global user.email "danger@example.com"
  - git config --global user.name "Danger McShane"
  - bundle exec rake spec
  - bundle exec danger --verbose
  - bundle exec danger init --mousey --impatient

matrix:
  fast_finish: true
  exclude:
    - rvm: 2.1.9
      after_success:
        - "[ ! -z $TRAVIS_TAG ] && bundle exec chandler push $TRAVIS_TAG"
    - rvm: 2.0
      after_success:
        - "[ ! -z $TRAVIS_TAG ] && bundle exec chandler push $TRAVIS_TAG"
