# frozen_string_literal: true

module Danger
  module OutputRegistry
    module Handlers
      module GitLab
        # Configuration constants for GitLab handlers.
        #
        module GitLabConfig
          # Header used to identify Danger-generated comments
          MR_REVIEW_HEADER = "<!-- Danger: generated by Danger -->"

          # Section titles
          ERRORS_SECTION_TITLE = "Errors"
          WARNINGS_SECTION_TITLE = "Warnings"
          MESSAGES_SECTION_TITLE = "Messages"

          # Type mappings for violations
          TYPE_MAPPINGS = {
            error: { emoji: "no_entry_sign", level: "error" },
            warning: { emoji: "warning", level: "warning" },
            message: { emoji: "book", level: "notice" }
          }.freeze
        end
      end
    end
  end
end
